require:  
- rubocop-rspec
- rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*.rake'
  ExcludedMethods: ['describe']

Metrics/LineLength:
  Max: 120 # aim for 80, but allow some extra length.
  Exclude:
    - 'config/routes.rb'

Metrics/MethodLength:
  ExcludedMethods: ['change']

RSpec/ExampleLength:
  Exclude:
    - 'spec/serializers/**/*'
